/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "biglybt-parent"
include(":biglybt-ui")
include(":biglybt-core")
project(":biglybt-ui").projectDir = file("uis")
project(":biglybt-core").projectDir = file("core")
