/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.commons.cli.commons.cli)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.assertj.assertj.core)
}

description = "BiglyBT - Core"

sourceSets {
    main {
        resources {
            srcDirs("resources", "src", "../clientfiles")
            include("**/*.properties", "**/*.png", "**/*.gif", "**/*.jpg", "**/*.html", "**/*.css", "**/*.xml", "**/*.txt", "META-INF/**")
            exclude("../clientfiles/META-INF/**")
        }
    }
}

tasks.named<ProcessResources>("processResources") {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
